# Cloud Build configuration to build and (optionally) deploy the HTML-render backend.
# Set substitutions when creating the trigger or running builds:
# _SERVICE_NAME: the Cloud Run service name (e.g., family-display-backend)
# _REGION: e.g., australia-southeast1
# _PROJECT_ID: the GCP project ID
# _IMAGE_NAME: container name (default: family-html)

substitutions:
  _SERVICE_NAME: "family-display-backend"
  _REGION: "australia-southeast1"
  _PROJECT_ID: "$PROJECT_ID"
  _IMAGE_NAME: "family-html"

steps:
  # Build container from backend/ folder
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}", "."]
    dir: "backend"

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"]

  # Optional: Deploy to Cloud Run (comment out if you only want to build/push)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars
      - GCS_BUCKET=family-display-packs,ADMIN_TOKEN=adm_123456,PUBLIC_BASE_URL=https://REPLACE-WITH-RUN-URL

images:
  - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"
