substitutions:
  _SERVICE_NAME: "family-display-backend-867804884116"
  _REGION: "australia-southeast1"
  _IMAGE_NAME: "family-html"
  _PROJECT_ID: "$PROJECT_ID"

steps:
  # 1) Build from backend/ using its Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f", "backend/Dockerfile",             # <— explicit Dockerfile path
        "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}",
        "backend"                               # <— build context is backend/
      ]

  # 2) Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"]

  # 3) Deploy to your active service
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","${_SERVICE_NAME}",
        "--image","gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--quiet",
        "--set-env-vars",
        "PUBLIC_BASE_URL=https://family-display-backend-867804884116.australia-southeast1.run.app,DEFAULT_DEVICE_ID=familydisplay,DEFAULT_CITY=Darwin, AU,DEFAULT_UNITS=metric,TIMEZONE=Australia/Adelaide"
      ]

images:
  - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"

timeout: "1200s"
