# Cloud Build: build + push + deploy from backend/ directory
# Edit _SERVICE_NAME, _REGION as needed.

substitutions:
  _SERVICE_NAME: "family-display-backend"
  _REGION: "australia-southeast1"
  _PROJECT_ID: "$PROJECT_ID"
  _IMAGE_NAME: "family-html"

steps:
  # Build container from backend/ folder
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}", "."]
    dir: "backend"

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars
      - >
        GCS_BUCKET=family-display-packs,
        ADMIN_TOKEN=adm_123456,
        PUBLIC_BASE_URL=https://REPLACE-WITH-RUN-URL,
        DEFAULT_DEVICE_ID=familydisplay,
        DEFAULT_CITY=Darwin, AU,
        DEFAULT_UNITS=metric,
        TIMEZONE=Australia/Adelaide

images:
  - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"